language: node_js
node_js:
  - 14
dist: trusty
sudo: required
branches:
  only:
  - develop
  - feature/ng10
before_script:
  - npm install -g @angular/cli
script:
  - ng lint
  - npm run lib:build
  - npm test

# deploy to registry ...
