language: node_js
node_js:
  - 14
dist: trusty
sudo: required
branches:
  only:
  - develop
before_script:
  - npm install -g @angular/cli
script:
  - ng lint
  - node --max_old_space_size=4096 ./node_modules/@angular/cli/bin/ng test
  - npm run lib:build

# deploy to registry ...
