language: node_js
node_js:
  - 14
dist: trusty
os: 
  - linux
branches:
  only:
  - develop
before_script:
  - npm install -g @angular/cli
script:
  - ng lint
  - npm run lib:build
  - npm test

# deploy to registry ...
