language: node_js
node_js:
  - 14
dist: trusty
os: 
  - linux
branches:
  only:
  - develop
before_script:
  - npm install -g @angular/cli
script:
  - ng lint
  - npm run lib:build
  - node --max_old_space_size=4096 ./node_modules/@angular/cli/bin/ng test

# deploy to registry ...
